# Titanic Dataset
<div style="
    border: 5px solid purple;
    border-radius: 8px;
    padding: 0px;
    margin: 10px 0;
    background-color: inherit;
    color: inherit;
">
</div>

In [4]:
import pandas as pd

### Importing data
<div style="
    border: 2px solid orange;
    border-radius: 8px;
    padding: 0px;
    margin: 10px 0;
    background-color: inherit;
    color: inherit;
">
</div>

In [7]:
#from a csv file
df = pd.read_csv("titanic.csv")

### 1. Dataset Overview
<div style="
    border: 2px solid orange;
    border-radius: 8px;
    padding: 0px;
    margin: 10px 0;
    background-color: inherit;
    color: inherit;
">
</div>

In [8]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
#how many columns and rows
df.shape

(891, 12)

### 2. Structure of the Dataset
<div style="
    border: 2px solid orange;
    border-radius: 8px;
    padding: 0px;
    margin: 10px 0;
    background-color: inherit;
    color: inherit;
">
</div>

In [10]:
#number of unique values
print(df.nunique())

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [11]:
#a more detailed overview, an information overview
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [12]:
#checking a random slice of the dataframe
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.00,1,1,11751,52.5542,D35,S
127,128,1,3,"Madsen, Mr. Fridtjof Arne",male,24.00,0,0,C 17369,7.1417,NaN,S
221,222,0,2,"Bracken, Mr. James H",male,27.00,0,0,220367,13.0000,NaN,S
699,700,0,3,"Humblen, Mr. Adolf Mathias Nicolai Olsen",male,42.00,0,0,348121,7.6500,F G63,S

### 3. Descriptive Statistics
<div style="
    border: 2px solid orange;
    border-radius: 8px;
    padding: 0px;
    margin: 10px 0;
    background-color: inherit;
    color: inherit;
">
</div>

In [13]:
#numeric coulnms
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [14]:
#getting statistics on categorical/object columns
obj_cols = df.select_dtypes(include='object').columns
print(f"This dataset has {len(obj_cols)} object columns:", list(obj_cols))

This dataset has 5 object columns: ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [16]:
#detailed statistics on object data
for col in df.select_dtypes(include='object'):
    print(f"\nColumn: {col}")
    print("Count of non-null values:", df[col].count()) 
    print("Number of unique values:", df[col].nunique())
    print("Most frequent value:", df[col].value_counts().idxmax())
    print("Most frequent value (frequency):", df[col].value_counts().max())
    print("Least frequent value:", df[col].value_counts().idxmin())
    print("Least frequent value (frequency):", df[col].value_counts().min())

Column: Name
Count of non-null values: 891
Number of unique values: 891
Most frequent value: Braund, Mr. Owen Harris
Most frequent value (frequency): 1
Least frequent value: Braund, Mr. Owen Harris
Least frequent value (frequency): 1

Column: Sex
Count of non-null values: 891
Number of unique values: 2
Most frequent value: male
Most frequent value (frequency): 577
Least frequent value: female
Least frequent value (frequency): 314

Column: Ticket
Count of non-null values: 891
Number of unique values: 681
Most frequent value: 347082
Most frequent value (frequency): 7
Least frequent value: SC/PARIS 2149
Least frequent value (frequency): 1

Column: Cabin
Count of non-null values: 204
Number of unique values: 147
Most frequent value: G6
Most frequent value (frequency): 4
Least frequent value: E46
Least frequent value (frequency): 1

Column: Embarked
Count of non-null values: 889
Number of unique values: 3
Most frequent value: S
Most frequent value (frequency): 644
Least frequent value: Q
Least frequent value (frequency): 77

### 4. Missing Values and Duplicates
<div style="
    border: 2px solid orange;
    border-radius: 8px;
    padding: 0px;
    margin: 10px 0;
    background-color: inherit;
    color: inherit;
">
</div>

In [17]:
#checking duplicates in the dataframe
df.duplicated().sum()
print(f"This dataset has {int(df.duplicated().sum())} duplicates")

This dataset has 0 duplicates

In [18]:
#how many missing values
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [23]:
# % or missing values
df.isna().mean() * 100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [24]:
# total number of missing values
df.isna().sum().sum()

np.int64(866)

In [19]:
#checking the datatypes
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### 4. Data Consistency
<div style="
    border: 2px solid orange;
    border-radius: 8px;
    padding: 0px;
    margin: 10px 0;
    background-color: inherit;
    color: inherit;
">
</div>

In [20]:
# Are there mixed value types in a column?
for col in df.columns:
    types = df[col].apply(type).value_counts()
    if len(types) > 1:
        print(f"{col}: mixed types -> {types.index.tolist()}")
    else:
        print(f"{col}: No mixed types")

PassengerId: No mixed types
Survived: No mixed types
Pclass: No mixed types
Name: No mixed types
Sex: No mixed types
Age: No mixed types
SibSp: No mixed types
Parch: No mixed types
Ticket: No mixed types
Fare: No mixed types
Cabin: mixed types -> [<class 'float'>, <class 'str'>]
Embarked: mixed types -> [<class 'str'>, <class 'float'>]

In [22]:
# Are string column clean?
for col in df.select_dtypes(include='object').columns:
    errors = df[col].str.contains(r'[^a-zA-Z\s]', na=False).sum()
    if errors > 0:
        print(f"{col}: {errors} rows with non-alphabetic characters")
    else:
        print(f"{col}: No errors")

Name: 891 rows with non-alphabetic characters
Sex: No errors
Ticket: 887 rows with non-alphabetic characters
Cabin: 200 rows with non-alphabetic characters
Embarked: No errors

### 6. Next steps
<div style="
    border: 2px solid orange;
    border-radius: 8px;
    padding: 0px;
    margin: 10px 0;
    background-color: inherit;
    color: inherit;
">
</div>

In [26]:
# create a subset from part of initial DF
# number of survived passengers
survived_count = df['Survived'].value_counts()
survived_df = pd.DataFrame(survived_count) #converting the object into a Data Frame
survived_df = survived_df.reset_index(drop=False)
survived_df

   Survived  count
0         0    549
1         1    342