In [2]:
# ASDA week 2 - dataset 1
import pandas as pd

In [3]:
# importing data from .csv
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
housing_data = pd.read_csv('/Users/tejas/Desktop/Data Science/ASDA/Group/ASDA_2025_Group_3_Portfolio/additional_materials/housing.csv', header=None, delimiter=r"\s+", names=column_names)
housing_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [4]:
# number of (rows, columns)
housing_data.shape

(506, 14)

In [5]:
# Structure of dataset
housing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [6]:
# unique values in columns
housing_data.nunique()

CRIM       504
ZN          26
INDUS       76
CHAS         2
NOX         81
RM         446
AGE        356
DIS        412
RAD          9
TAX         66
PTRATIO     46
B          357
LSTAT      455
MEDV       229
dtype: int64

In [7]:
# Descriptive statastucs => Numeric columns
statistics = pd.DataFrame({
    "Count": housing_data.count(),
    "Mean": housing_data.mean(),
    "Standard Deviation": housing_data.std(),
    "Min": housing_data.min(),
    "25%": housing_data.quantile(0.25),
    "50%": housing_data.quantile(0.5),
    "75%": housing_data.quantile(0.75),
    "Max": housing_data.max()
})
statistics

# Transpose the DataFrame to swap rows and columns
statistics_transposed = statistics.T
# Results
statistics_transposed

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
Count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
Mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
Standard Deviation,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
Min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
Max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [9]:
# Categorical / Object Columns
categorical_cols = ["CHAS", "RAD"]

categorical = pd.DataFrame({
    "Count": housing_data[categorical_cols].count(),
    "Number of Unique Values": housing_data[categorical_cols].nunique(),
    "Most Frequent Value": housing_data[categorical_cols].mode().iloc[0],
    "Most Frequent Value (Frequency)": [
        housing_data[col].value_counts().iloc[0] for col in categorical_cols
    ],
    "Least Frequent Value": [
        housing_data[col].value_counts().index[-1] for col in categorical_cols
    ],
    "Least Frequent Value (Frequency)": [
        housing_data[col].value_counts().iloc[-1] for col in categorical_cols
    ]
})

categorical

# Transpose the DataFrame to swap rows and columns
categorical_transposed = categorical.T
# results
categorical_transposed

                                  CHAS  RAD
Count                              506  506
Number of Unique Values              2    9
Most Frequent Value                  0   24
Most Frequent Value (Frequency)    471  132
Least Frequent Value                 1    7
Least Frequent Value (Frequency)    35   17

In [10]:
# missing values and duplicates 
housing_data_null_duplicates = pd.DataFrame({
    "missing count" : housing_data.isnull().sum(),
    "% Missing" : housing_data.isnull().values.any()
})
housing_data_null_duplicates

         missing count  % Missing
CRIM                 0      False
ZN                   0      False
INDUS                0      False
CHAS                 0      False
NOX                  0      False
RM                   0      False
AGE                  0      False
DIS                  0      False
RAD                  0      False
TAX                  0      False
PTRATIO              0      False
B                    0      False
LSTAT                0      False
MEDV                 0      False

In [11]:
# missing values and percentage of missing values 
total_missing = housing_data.isnull().sum().sum()
percent_missing = (total_missing / housing_data.size) * 100
print(total_missing)
print(percent_missing)

0
0.0

In [12]:
# Duplicate values and percentage of duplicate values 
duplicated_rows = housing_data.duplicated().sum()
percent_duplicates = (duplicated_rows / len(housing_data)) * 100
print(duplicated_rows)
print(percent_duplicates)

0
0.0

In [13]:
# Dataset 2
titanic_data = pd.read_csv("/Users/tejas/Desktop/Data Science/ASDA/Group/ASDA_2025_Group_3_Portfolio/additional_materials/Titanic-Dataset.csv")
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
# number of (rows, columns)
titanic_data.shape

(891, 12)

In [15]:
# Structure of the dataset
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [16]:
# unique values
titanic_data.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [17]:
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [18]:
# Descriptive statastucs => Numeric columns
numeric_data_columns = ["PassengerId", "Survived", "Pclass", "Age", "SibSp", "Parch", "Fare"]
numeric_columns = pd.DataFrame({
    "Count": titanic_data[numeric_data_columns].count(),
    "Mean": titanic_data[numeric_data_columns].mean(),
    "Standard Deviation": titanic_data[numeric_data_columns].std(),
    "Min": titanic_data[numeric_data_columns].min(),
    "25%": titanic_data[numeric_data_columns].quantile(0.25),
    "50%": titanic_data[numeric_data_columns].quantile(0.5),
    "75%": titanic_data[numeric_data_columns].quantile(0.75),
    "Max": titanic_data[numeric_data_columns].max()
})
numeric_columns


# Transpose the DataFrame to swap rows and columns
numeric_columns_transposed = numeric_columns.T
# results
numeric_columns_transposed

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
Mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
Standard Deviation,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
Min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
Max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [19]:
# Categorical / Object Columns
categorical_columns = ["Name", "Sex", "Ticket", "Cabin", "Embarked"]

categorical_data = pd.DataFrame({
    "Count": titanic_data[categorical_columns].count(),
    "Number of Unique Values": titanic_data[categorical_columns].nunique(),
    "Most Frequent Value": titanic_data[categorical_columns].mode().iloc[0],
    "Most Frequent Value (Frequency)": [
        titanic_data[col].value_counts().iloc[0] for col in categorical_columns
    ],
    "Least Frequent Value": [
        titanic_data[col].value_counts().index[-1] for col in categorical_columns
    ],
    "Least Frequent Value (Frequency)": [
        titanic_data[col].value_counts().iloc[-1] for col in categorical_columns
    ]
})

categorical_data

# Transpose the DataFrame to swap rows and columns
categorical_data_transposed = categorical_data.T
# results
categorical_data_transposed

,Name,Sex,Ticket,Cabin,Embarked
Count,891,891,891,204,889
Number of Unique Values,891,2,681,147,3
Most Frequent Value,"Abbing, Mr. Anthony",male,1601,B96 B98,S
Most Frequent Value (Frequency),1,577,7,4,644
Least Frequent Value,"Dooley, Mr. Patrick",female,370376,C148,Q
Least Frequent Value (Frequency),1,314,1,1,77

In [20]:
# missing values and duplicates
missing_data_2 = pd.DataFrame({
    "Missing" : titanic_data.isnull().sum(),
    "% Missing" : titanic_data.isnull().values.any()
})
missing_data_2

             Missing  % Missing
PassengerId        0       True
Survived           0       True
Pclass             0       True
Name               0       True
Sex                0       True
Age              177       True
SibSp              0       True
Parch              0       True
Ticket             0       True
Fare               0       True
Cabin            687       True
Embarked           2       True

In [24]:
# missing values and percentage of missing values 
total_missing_2 = titanic_data.isnull().sum().sum()
percent_missing_2 = (total_missing_2 / titanic_data.size) * 100
print(total_missing_2)
print(percent_missing_2)

866
8.099513655069211

In [26]:
# Duplicate values and percentage of duplicate values 
duplicated_rows_2 = titanic_data.duplicated().sum()
percent_duplicates_2 = (duplicated_rows_2 / len(titanic_data)) * 100
print(duplicated_rows_2)
print(percent_duplicates_2)

0
0.0